FROM maven:3.8.4-openjdk-17-slim

# COPY ./jars/* /usr/jars/
# COPY ./* /ideas-app/
# WORKDIR /ideas-app
# RUN mvn install -T 1C
# RUN mvn package -T 1C -o -Dmaven.test.skip=true

# ENTRYPOINT [ "" ]
# # CMD ["java", "-jar", "-Dspring.profiles.active=test", "/app/target/gs-spring-boot-docker-0.1.0.jar"]
# # CMD ["cp", "/ideas-app/target/ideas-studio-0.8-SNAPSHOT.jar", "/usr/jars"]
# CMD tail -f /dev/null