FROM docker4ideas/module:develop

RUN apt update
RUN apt install -y texlive-latex-base
COPY ideas-latex-module /ideas/latex-module
RUN cd /ideas/latex-module && mvn package

CMD cd /ideas/latex-module && mvn spring-boot:run

# Da un fallo al ejecutar los tests.